name: Build and Deploy
on:
  push:
    branches:
      - master
  jobs:
    build-and-deploy:
      # This is telling GitHub to run the workflow on the latest version of Ubuntu.
      runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install and Test Client
        working-directory: ./frontend
        run: |
          npm install
          npm run test
      - name: Install and Test Server
        working-directory: ./backend
        run: |
          npm install
          npm run test