name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Test Client
        working-directory: ./frontend
        run: |
          npm install

      - name: Install and Test Server
        working-directory: ./backend
        run: |
          npm install

      - name: Build Frontend Docker Image
        working-directory: ./frontend
        # Build image with tag amoghnagar123/foodiee:frontend
        run: |
          docker build -t amoghnagar123/foodiee:frontend-${{github.run_number}} .
      
      - name: Build Backend Docker Image
        working-directory: ./backend
        # Build image with tag amoghnagar123/foodiee:backend
        run: |
          docker build -t amoghnagar123/foodiee:backend-${{github.run_number}} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push amoghnagar123/foodiee:frontend-${{github.run_number}}
          docker push amoghnagar123/foodiee:backend-${{github.run_number}}